STATUS_OPEN = 1
STATUS_IN_PROGRESS = 2
STATUS_RESOLVED = 3
STATUS_CLOSED = 4
STATUS_ESCALATED = 5

STATUS_ACTIVE = (STATUS_OPEN, STATUS_IN_PROGRESS, STATUS_ESCALATED)
STATUS_ARCHIVED = (STATUS_RESOLVED, STATUS_CLOSED)
STATUS_UNASSIGNED = STATUS_ACTIVE

ALLOWED_OPERATOR_TRANSITIONS = {
    STATUS_OPEN: [STATUS_IN_PROGRESS],
    STATUS_IN_PROGRESS: [STATUS_RESOLVED],
    STATUS_RESOLVED: [],
    STATUS_CLOSED: [],
    STATUS_ESCALATED: [],
}

SEVERITY_LOW = 1
SEVERITY_MEDIUM = 2
SEVERITY_HIGH = 3
SEVERITY_CRITICAL = 4
